"""Pydantic schemas and data contracts for the LLM Harness."""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class SubAgentRole(str, Enum):
    """Roles of agents participating in the Harness execution loop."""
    DISPATCHER = "dispatcher"
    DEVELOPER = "developer"
    REVIEWER = "reviewer"
    TESTER = "tester"


class Skill(BaseModel):
    """Representation of an externally defined skill."""
    name: str = Field(..., description="Unique machine-readable skill identifier")
    title: str = Field(..., description="Human-readable title")
    version: str = Field("1.0.0", description="Skill semver version")
    target_agents: List[str] = Field(default_factory=list, description="Agents this skill can be injected into")
    description: str = Field(..., description="Short explanation of the skill domain")
    tags: List[str] = Field(default_factory=list, description="Categorization tags")
    content: str = Field(..., description="Full instructional markdown/guidelines content")


class ReviewSeverity(str, Enum):
    """Severity levels for code review findings."""
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class ReviewIssue(BaseModel):
    """Single issue discovered by ReviewerAgent."""
    severity: ReviewSeverity
    rule_violated: str = Field(..., description="Skill guideline or rule name violated")
    description: str = Field(..., description="Detailed description of the issue")
    suggestion: str = Field(..., description="Actionable fix recommendation")


class ReviewReport(BaseModel):
    """Structured report produced by ReviewerAgent."""
    status: str = Field(..., description="'approved' or 'changes_requested'")
    summary: str = Field(..., description="Executive summary of the review")
    issues: List[ReviewIssue] = Field(default_factory=list, description="List of detected issues")

    @property
    def is_approved(self) -> bool:
        return self.status.lower() == "approved" or len([i for i in self.issues if i.severity == ReviewSeverity.CRITICAL]) == 0


class TaskStep(BaseModel):
    """An individual execution step in the decomposed task plan."""
    step_id: int
    title: str
    role: SubAgentRole
    skill_names: List[str] = Field(default_factory=list, description="Skills to inject dynamically for this step")
    instructions: str = Field(..., description="Specific objective for the subagent")


class ExecutionPlan(BaseModel):
    """Decomposed multi-step execution plan generated by the Root Dispatcher."""
    task_description: str
    rationale: str = Field(..., description="Chain-of-thought rationale behind decomposition")
    steps: List[TaskStep]


class AgentExecutionResult(BaseModel):
    """Output bundle returned by a subagent execution step."""
    step_id: int
    role: SubAgentRole
    injected_skills: List[str] = Field(default_factory=list)
    raw_output: str
    code_artifacts: Dict[str, str] = Field(default_factory=dict, description="Generated code/test files")
    review_report: Optional[ReviewReport] = None
    execution_time_sec: float = 0.0
